// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_actions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const logAdminCancelReservation = `-- name: LogAdminCancelReservation :one
INSERT INTO admin_actions (id, admin_user_id, action, target_reservation_id, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    'cancel_reservation',
    $2,
    NOW()
)
RETURNING id, admin_user_id, action, target_reservation_id, created_at
`

type LogAdminCancelReservationParams struct {
	AdminUserID         uuid.UUID
	TargetReservationID uuid.NullUUID
}

func (q *Queries) LogAdminCancelReservation(ctx context.Context, arg LogAdminCancelReservationParams) (AdminAction, error) {
	row := q.db.QueryRowContext(ctx, logAdminCancelReservation, arg.AdminUserID, arg.TargetReservationID)
	var i AdminAction
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.TargetReservationID,
		&i.CreatedAt,
	)
	return i, err
}
