// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AdminAction struct {
	ID                  uuid.UUID
	AdminUserID         uuid.UUID
	Action              string
	TargetReservationID uuid.NullUUID
	CreatedAt           time.Time
}

type Category struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsActive  bool
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Reservation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CategoryID uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
	Note       sql.NullString
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Role           string
}
