// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelReservation = `-- name: CancelReservation :one
UPDATE reservations
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, start_time, end_time, note, status, created_at, updated_at
`

type CancelReservationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, cancelReservation, arg.ID, arg.UserID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelReservationByAdmin = `-- name: CancelReservationByAdmin :one
UPDATE reservations
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, category_id, start_time, end_time, note, status, created_at, updated_at
`

func (q *Queries) CancelReservationByAdmin(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, cancelReservationByAdmin, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkReservationConflict = `-- name: CheckReservationConflict :one
SELECT EXISTS 
(SELECT 1 FROM reservations 
 WHERE category_id = $1 
 AND status = 'confirmed' 
 AND start_time < $2 
 AND end_time > $3)
`

type CheckReservationConflictParams struct {
	CategoryID   uuid.UUID
	NewEndTime   time.Time
	NewStartTime time.Time
}

func (q *Queries) CheckReservationConflict(ctx context.Context, arg CheckReservationConflictParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkReservationConflict, arg.CategoryID, arg.NewEndTime, arg.NewStartTime)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (id, user_id, category_id, start_time, end_time, note, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, user_id, category_id, start_time, end_time, note, status, created_at, updated_at
`

type CreateReservationParams struct {
	UserID     uuid.UUID
	CategoryID uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
	Note       sql.NullString
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.UserID,
		arg.CategoryID,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllReservations = `-- name: GetAllReservations :many
SELECT id, user_id, category_id, start_time, end_time, note, status, created_at, updated_at FROM reservations
`

func (q *Queries) GetAllReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationsByUser = `-- name: GetReservationsByUser :many
SELECT id, user_id, category_id, start_time, end_time, note, status, created_at, updated_at FROM reservations
WHERE user_id = $1
`

func (q *Queries) GetReservationsByUser(ctx context.Context, userID uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
