package main

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/deanhattenhauer/reservation-api/internal/auth"
	"github.com/deanhattenhauer/reservation-api/internal/database"
	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name 	  string 	`json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (cfg *apiConfig) handlerCreateCategory(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		Name string `json:"name"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	// Authenticate user with token
	_, role, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
		}

	if role != "admin"{
		respondWithError(w, http.StatusForbidden, "Unauthorized access", nil)
		return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	category, err := cfg.dbQueries.CreateCategory(r.Context(), params.Name)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create category", err)
		return
	}

	// Map database.Category to the API Category struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusCreated, Category{
		ID:        category.ID,
		Name:      category.Name,
		CreatedAt: category.CreatedAt,
		UpdatedAt: category.UpdatedAt,
	})
}

func (cfg *apiConfig) handlerGetActiveCategories(w http.ResponseWriter, r *http.Request) {

	activeCategories, err := cfg.dbQueries.GetActiveCategories(r.Context())
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "could not get active categories", err)
		return
	}

	newSlice := []Category{}

	//Map database.Category to API Category struct to ensure correct JSON key casing via struct tags.
	for _, category := range activeCategories {
		newSlice = append(newSlice, Category{
		ID:        category.ID,
		Name:      category.Name,
		CreatedAt: category.CreatedAt,
		UpdatedAt: category.UpdatedAt,
		})
	}

	respondWithJSON(w, http.StatusOK, newSlice)
}

func (cfg *apiConfig) handlerUpdateCategoryName(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		Name string `json:"name"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	// Authenticate user with token
	_, role, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
		}

	if role != "admin"{
		respondWithError(w, http.StatusForbidden, "Unauthorized access", nil)
		return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	categoryID, err := uuid.Parse(r.PathValue("categoryID"))
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't parse category", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	category, err := cfg.dbQueries.UpdateCategoryName(r.Context(), database.UpdateCategoryNameParams{ID: categoryID, Name: params.Name})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't update category", err)
		return
	}

	// Map database.Category to the API Category struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusOK, Category{
		ID:        category.ID,
		Name:      category.Name,
		CreatedAt: category.CreatedAt,
		UpdatedAt: category.UpdatedAt,
		IsActive: category.IsActive,
	})
}

func (cfg *apiConfig) handlerSetCategoryActive(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		IsActive bool `json:"is_active"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	// Authenticate user with token
	_, role, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
		}

	if role != "admin"{
		respondWithError(w, http.StatusForbidden, "Unauthorized access", nil)
		return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	categoryID, err := uuid.Parse(r.PathValue("categoryID"))
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't parse category", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	category, err := cfg.dbQueries.SetCategoryActive(r.Context(), database.SetCategoryActiveParams{IsActive: params.IsActive, ID: categoryID})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't update category", err)
		return
	}

	// Map database.Category to the API Category struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusOK, Category{
		ID:        category.ID,
		Name:      category.Name,
		CreatedAt: category.CreatedAt,
		UpdatedAt: category.UpdatedAt,
		IsActive: category.IsActive,
	})
}