package main

import (
	"database/sql"
	"encoding/json"
	"net/http"
	"time"

	"github.com/deanhattenhauer/reservation-api/internal/auth"
	"github.com/deanhattenhauer/reservation-api/internal/database"
	"github.com/google/uuid"
)
type Reservation struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	StartTime  time.Time `json:"start_time"`
	EndTime    time.Time `json:"end_time"`
	Note       string    `json:"note"`
	Status	   string	 `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (cfg *apiConfig) handlerCreateReservation(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		CategoryID uuid.UUID `json:"category_id"`
		StartTime  time.Time `json:"start_time"`
		EndTime    time.Time `json:"end_time"`
		Note       string `json:"note"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	reservation, err := cfg.dbQueries.CreateReservation(r.Context(), database.CreateReservationParams{UserID: userID, CategoryID: params.CategoryID, StartTime: params.StartTime, EndTime: params.EndTime, Note: sql.NullString{String: params.Note, Valid: params.Note != ""}})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create category", err)
		return
	}

	// Map database.Reservation to the API Reservation struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusCreated, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
	})
}

func (cfg *apiConfig) handlerGetReservationsByUser(w http.ResponseWriter, r *http.Request) {
	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	
	// Fetching reservations — ID and timestamps are generated by Postgres.
	reservations, err := cfg.dbQueries.GetReservationsByUser(r.Context(), userID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch reservations", err)
		return
	}

	newSlice := []Reservation{}

	//Map database.Reservation to API Reservation struct to ensure correct JSON key casing via struct tags.
	for _, reservation := range reservations {
		newSlice = append(newSlice, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
		})
	}

		respondWithJSON(w, http.StatusOK, newSlice)
}

func (cfg *apiConfig) handlerGetAllReservations(w http.ResponseWriter, r *http.Request) {
	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	_, role, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	if role != "admin"{
		respondWithError(w, http.StatusForbidden, "Unauthorized access", nil)
		return
	}

	// Fetching reservations — ID and timestamps are generated by Postgres.
	reservations, err := cfg.dbQueries.GetAllReservations(r.Context())
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch reservations", err)
		return
	}

	newSlice := []Reservation{}

	//Map database.Reservation to API Reservation struct to ensure correct JSON key casing via struct tags.
	for _, reservation := range reservations {
		newSlice = append(newSlice, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
		})
	}

		respondWithJSON(w, http.StatusOK, newSlice)
}