package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/deanhattenhauer/reservation-api/internal/auth"
	"github.com/deanhattenhauer/reservation-api/internal/database"
	"github.com/google/uuid"
)
type Reservation struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	StartTime  time.Time `json:"start_time"`
	EndTime    time.Time `json:"end_time"`
	Note       string    `json:"note"`
	Status	   string	 `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (cfg *apiConfig) handlerCreateReservation(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		CategoryID uuid.UUID `json:"category_id"`
		StartTime  time.Time `json:"start_time"`
		EndTime    time.Time `json:"end_time"`
		Note       string `json:"note"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	// Check to see if a scheduling conflict exists
	conflictExists, err := cfg.dbQueries.CheckReservationConflict(r.Context(), database.CheckReservationConflictParams{CategoryID: params.CategoryID, NewStartTime: params.StartTime, NewEndTime: params.EndTime})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch reservations", err)
		return
	}
	if conflictExists {
		respondWithError(w, http.StatusConflict, "this time slot is taken", nil)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	reservation, err := cfg.dbQueries.CreateReservation(r.Context(), database.CreateReservationParams{UserID: userID, CategoryID: params.CategoryID, StartTime: params.StartTime, EndTime: params.EndTime, Note: sql.NullString{String: params.Note, Valid: params.Note != ""}})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create category", err)
		return
	}

	// Get user email for confirmation email
	userEmail, err := cfg.dbQueries.GetUserByID(r.Context(), userID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch email", err)
		return
	}

	// Fetch category name for confirmation email
	categoryName, err := cfg.dbQueries.GetCategoryName(r.Context(), params.CategoryID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch name", err)
		return
	}

	// Send creation confirmation email
	subject := fmt.Sprintf("Your %s reservation is confirmed", categoryName.Name)
	html := fmt.Sprintf(
    	"<h1>Your reservation is confirmed!</h1><p><strong>Details regarding your %s reservation:</strong></p><ul><li>Date: %s - %s</li><li>Note: %s</li></ul>",
		categoryName.Name,
    	reservation.StartTime.Format("January 2, 2006 3:04 PM"),
    	reservation.EndTime.Format("January 2, 2006 3:04 PM"),
		reservation.Note.String,
	)
	go SendEmail(cfg.resendAPIKey, userEmail.Email, subject, html)

	// Map database.Reservation to the API Reservation struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusCreated, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
	})
}

func (cfg *apiConfig) handlerGetReservationsByUser(w http.ResponseWriter, r *http.Request) {
	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	
	// Fetching reservations — ID and timestamps are generated by Postgres.
	reservations, err := cfg.dbQueries.GetReservationsByUser(r.Context(), userID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch reservations", err)
		return
	}

	newSlice := []Reservation{}

	//Map database.Reservation to API Reservation struct to ensure correct JSON key casing via struct tags.
	for _, reservation := range reservations {
		newSlice = append(newSlice, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
		})
	}

		respondWithJSON(w, http.StatusOK, newSlice)
}

func (cfg *apiConfig) handlerGetAllReservations(w http.ResponseWriter, r *http.Request) {

	// Fetching reservations — ID and timestamps are generated by Postgres.
	reservations, err := cfg.dbQueries.GetAllReservations(r.Context())
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch reservations", err)
		return
	}

	newSlice := []Reservation{}

	//Map database.Reservation to API Reservation struct to ensure correct JSON key casing via struct tags.
	for _, reservation := range reservations {
		newSlice = append(newSlice, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
		})
	}

		respondWithJSON(w, http.StatusOK, newSlice)
}

func (cfg *apiConfig) handlerCancelReservation(w http.ResponseWriter, r *http.Request) {
	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}

	// Get reservation ID from URL path
	reservationID, err := uuid.Parse(r.PathValue("reservationID"))
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't parse ID", err)
		return
	}

	// Persist the user to the database - ID and timestamps are generated by Postgres.
	reservation, err := cfg.dbQueries.CancelReservation(r.Context(), database.CancelReservationParams{ID: reservationID, UserID: userID})
	if err != nil {
		respondWithError(w, http.StatusNotFound, "reservation not found", err)
		return
	}

	// Fetch user email for cancellation email
	userEmail, err := cfg.dbQueries.GetUserByID(r.Context(), userID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch email", err)
		return
	}

	// Fetch category name for cancellation email
	categoryName, err := cfg.dbQueries.GetCategoryName(r.Context(), reservation.CategoryID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch name", err)
		return
	}

	// Send cancellation email
	subject := fmt.Sprintf("Your %s reservation has been cancelled", categoryName.Name)
	html := fmt.Sprintf(
    	"<h1>Your reservation has been cancelled.</h1><p><strong>Details regarding your %s cancellation:</strong></p><ul><li>Date: %s - %s</li><li>Note: %s</li></ul>",
		categoryName.Name,
    	reservation.StartTime.Format("January 2, 2006 3:04 PM"),
    	reservation.EndTime.Format("January 2, 2006 3:04 PM"),
		reservation.Note.String,
	)
	go SendEmail(cfg.resendAPIKey, userEmail.Email, subject, html)

	// Map database.Reservation to the API Reservation struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusOK, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
	})
}

func (cfg *apiConfig) handlerCancelReservationByAdmin(w http.ResponseWriter, r *http.Request) {
	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	adminUserID, role, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
	respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
	return
	}


	if role != "admin"{
		respondWithError(w, http.StatusForbidden, "Unauthorized access", nil)
		return
	}

	// Get reservation ID from URL path
	reservationID, err := uuid.Parse(r.PathValue("reservationID"))
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't parse ID", err)
		return
	}

	// Persist the user to the database - ID and timestamps are generated by Postgres.
	reservation, err := cfg.dbQueries.CancelReservationByAdmin(r.Context(), reservationID)
	if err != nil {
		respondWithError(w, http.StatusNotFound, "reservation not found", err)
		return
	}
	
	//Log when admin cancels a reservation
	_, err = cfg.dbQueries.LogAdminCancelReservation(r.Context(), database.LogAdminCancelReservationParams{AdminUserID: adminUserID, TargetReservationID: uuid.NullUUID{UUID: reservationID, Valid: true}})
	if err != nil {
		slog.Error("could not log admin action", "error", err, "admin_id", adminUserID, "reservation_id", reservationID)
	}

	// Fetch user email for cancellation email
	userEmail, err := cfg.dbQueries.GetUserByID(r.Context(), reservation.UserID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch email", err)
		return
	}

	// Fetch category name for cancellation email
	categoryName, err := cfg.dbQueries.GetCategoryName(r.Context(), reservation.CategoryID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't fetch name", err)
		return
	}

	// Send cancellation email
	subject := fmt.Sprintf("Your %s reservation has been cancelled", categoryName.Name)
	html := fmt.Sprintf(
    	"<h1>Your reservation has been cancelled.</h1><p><strong>Details regarding your %s cancellation:</strong></p><ul><li>Date: %s - %s</li><li>Note: %s</li></ul>",
		categoryName.Name,
    	reservation.StartTime.Format("January 2, 2006 3:04 PM"),
    	reservation.EndTime.Format("January 2, 2006 3:04 PM"),
		reservation.Note.String,
	)
	go SendEmail(cfg.resendAPIKey, userEmail.Email, subject, html)

	// Map database.Reservation to the API Reservation struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusOK, Reservation{
		ID:         reservation.ID,
		UserID:     reservation.UserID,
		CategoryID: reservation.CategoryID,
		StartTime:  reservation.StartTime,
		EndTime:    reservation.EndTime,
		Note: 		reservation.Note.String,
		Status: 	reservation.Status,
		CreatedAt:  reservation.CreatedAt,
		UpdatedAt:  reservation.UpdatedAt,
	})
}
