package main

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/deanhattenhauer/reservation-api/internal/auth"
	"github.com/deanhattenhauer/reservation-api/internal/database"
	"github.com/google/uuid"
)

// User is the API representation of a Chirpy user.
// Mapped from database.User to control JSON key names via struct tags.
// Keeping this separate from the database model allows the API shape
// to evolve independently of the database schema.
type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
}

// handlerCreateUser creates a new user account with the provided email.
// Returns 201 Created with the full user object on success.
func (cfg *apiConfig) handlerCreateUser(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		Password string `json:"password"`
		Email string `json:"email"`
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}
	
	hash, err := auth.HashPassword(params.Password)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't hash password", err)
		return
	}

	// Persist the user to the database — ID and timestamps are generated by Postgres.
	user, err := cfg.dbQueries.CreateUser(r.Context(), database.CreateUserParams{HashedPassword: hash, Email: params.Email})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create user", err)
		return
	}

	// Map database.User to the API User struct before responding.
	// This decouples the JSON response shape from the internal database model.
	respondWithJSON(w, http.StatusCreated, User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	})
}

func (cfg *apiConfig) handlerUpdateUser(w http.ResponseWriter, r *http.Request) {

	// parameters defines the expected shape of the request body.
	type parameters struct {
		Password string `json:"password"`
		Email string `json:"email"`
	}

	// Get the token from the request headers
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Unable to get token header", err)
		return
	}

	// Authenticate user with token
	userID, _, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Couldn't validate token", err)
		return
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	// Hash new password
	hashedPassword, err := auth.HashPassword(params.Password)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't hash password", err)
		return
	}

	// Update user with new password
	user, err := cfg.dbQueries.UpdateUser(r.Context(), database.UpdateUserParams{Email: params.Email, HashedPassword: hashedPassword, ID: userID})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't update user", err)
		return
	}

	respondWithJSON(w, http.StatusOK, User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	})
}

func (cfg *apiConfig) handlerUpdateUserRole(w http.ResponseWriter, r *http.Request) {
	// parameters defines the expected shape of the request body.
	type parameters struct {
		Role string `json:"role"`
	}

	// Decode the request body — returns 500 if JSON is malformed or wrong types.
	decoder := json.NewDecoder(r.Body)
	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	userID, err := uuid.Parse(r.PathValue("userID"))
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't parse user", err)
		return
	}

	// Persist the user to the database - ID and timestamps are generated by Postgres.
	user, err := cfg.dbQueries.UpdateUserRole(r.Context(), database.UpdateUserRoleParams{ID: userID, Role: params.Role})
	if err != nil {
		respondWithError(w, http.StatusNotFound, "user not found", err)
		return
	}

	respondWithJSON(w, http.StatusOK, User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	})
}